- hosts: localhost
  become: true
  tasks:
    - name: Install Apache 2
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Enable mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
