- name: Print the users
  hosts: localhost
  gather_facts: 'no'
  vars_files:
    - users.yaml
  tasks:
    - name: Print User Details
      debug:
        msg: 'User: {{ item.name }} - {{ item.address.street }}'
      loop: '{{ users }}'
      when: item.name is defined