- hosts: all
  vars:
    salutations: Hello everyone!

  tasks:
    - name: Using Ansible variable
      debug:
        msg: "Sal: {{ salutations }}"
    
    - name: Print the greeting message
      debug:
        msg: "My Greetings: {{ greeting }}"

    - name: Print the custom number
      debug:
        msg: "My Number: {{ custom_number }}"

    - name: Nested Loop
      debug:
        msg: "Item 1 : {{ item.0}} - {{ item.1 }}"
      with_nested:
        - ['A', 'B', 'C']   
        - ['1']           