- name: Demo playbook for group vars testing
  hosts: all
  gather_facts: no

  tasks:
    - name: Print the greeting message
      debug:
        msg: "My Greetings: {{ greeting }}"

    - name: Print the custom number
      debug:
        msg: "My Number: {{ custom_number }}"
